// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the classes for AzureAgriFoodRPService. APIs documentation for Azure AgriFood Resource Provider
 * Service.
 */
package com.azure.resourcemanager.agrifood;
