// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

package com.azure.resourcemanager.agrifood.fluent.models;

import com.azure.core.annotation.Immutable;
import com.azure.resourcemanager.agrifood.models.ProvisioningState;
import com.fasterxml.jackson.annotation.JsonProperty;

/** FarmBeats ARM Resource properties. */
@Immutable
public final class FarmBeatsProperties {
    /*
     * Uri of the FarmBeats instance.
     */
    @JsonProperty(value = "instanceUri", access = JsonProperty.Access.WRITE_ONLY)
    private String instanceUri;

    /*
     * FarmBeats instance provisioning state.
     */
    @JsonProperty(value = "provisioningState", access = JsonProperty.Access.WRITE_ONLY)
    private ProvisioningState provisioningState;

    /**
     * Get the instanceUri property: Uri of the FarmBeats instance.
     *
     * @return the instanceUri value.
     */
    public String instanceUri() {
        return this.instanceUri;
    }

    /**
     * Get the provisioningState property: FarmBeats instance provisioning state.
     *
     * @return the provisioningState value.
     */
    public ProvisioningState provisioningState() {
        return this.provisioningState;
    }

    /**
     * Validates the instance.
     *
     * @throws IllegalArgumentException thrown if the instance is not valid.
     */
    public void validate() {
    }
}
