// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.
// Code generated by Microsoft (R) AutoRest Code Generator.

/**
 * Package containing the data models for AzureAgriFoodRPService. APIs documentation for Azure AgriFood Resource
 * Provider Service test.
 */
package com.azure.resourcemanager.agrifood.models;
