# NOTE: Please refer to https://aka.ms/azsdk/engsys/ci-yaml before editing this file.

trigger:
  branches:
    include:
      - main
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/agrifood/
    exclude:
      - sdk/agrifood/pom.xml
      - sdk/agrifood/azure-verticals-agrifood-farming/pom.xml

pr:
  branches:
    include:
      - main
      - feature/*
      - hotfix/*
      - release/*
  paths:
    include:
      - sdk/agrifood/
    exclude:
      - sdk/agrifood/pom.xml
      - sdk/agrifood/azure-verticals-agrifood-farming/pom.xml

extends:
  template: ../../eng/pipelines/templates/stages/archetype-sdk-client.yml
  parameters:
    ServiceDirectory: agrifood
    Artifacts:
      - name: azure-verticals-agrifood-farming
        groupId: com.azure
        safeName: azureverticalsagrifoodfarming
      - name: azure-resourcemanager-agrifood
        groupId: com.azure.resourcemanager
        safeName: azureresourcemanageragrifood
        releaseInBatch: ${{ parameters.release_azureresourcemanageragrifood }}

parameters:
  - name: release_azureresourcemanageragrifood
    displayName: azure-resourcemanager-agrifood
    type: boolean
    default: false
